services:
  feed-service:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.feed
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  user-service:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.user
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  api-gateway:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.gateway
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
    depends_on:
      - feed-service
      - user-service
