FROM golang:1.24.0

WORKDIR /app
COPY ./observability /observability
COPY ./feed-service/go.mod ./
COPY ./feed-service/go.sum ./
RUN go mod download
COPY ./feed-service .

CMD ["go", "run", "main.go"]
