FROM golang:1.24.0 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/api-gateway
RUN CGO_ENABLED=0 GOOS=linux go build -o api-gateway

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/api-gateway/api-gateway .
EXPOSE 2000
CMD ["./api-gateway"]