FROM golang:1.24.0 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/user-service
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user-service

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/user-service/user-service .
EXPOSE 4000
CMD ["./user-service"]