FROM golang:1.24.0 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/feed-service
RUN CGO_ENABLED=0 GOOS=linux go build -o feed-service

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/feed-service/feed-service .
EXPOSE 3000
CMD ["./feed-service"]